spring:
  datasource:
    url: jdbc:postgresql://ep-red-dream-a19i1shc.ap-southeast-1.aws.neon.tech/shopapp-db
    driver-class-name: org.postgresql.Driver
    username: shopapp-db_owner
    password: B1YjM0mthxJQ
