spring:
  application:
    name: shopapp
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8088

openapi:
  title: Shop APP API
  version: v1.0.0
  description: API documentation for the Shop App.
  serverUrl: http://localhost:8088
  serverName: Shop App Server

api:
  prefix: api/v1

jwt:
  expiration: 259200 #days: 30 = 30 * 24 * 60 * 60
  secretKey: HelloEveryOneMyNameZanzyWelcomeToJoinMyShopApp
