INSERT INTO categories (name) VALUE ('Buns');
INSERT INTO categories (name) VALUE ('Toasts');
INSERT INTO categories (name) VALUE ('Sandwiches');
INSERT INTO categories (name) VALUE ('Dry Cakes');
INSERT INTO categories (name) VALUE ('Cakes');
INSERT INTO categories (name) VALUE ('Cake Slices');
INSERT INTO categories (name) VALUE ('Seasonal Specials');
INSERT INTO categories (name) VALUE ('Pudding');
INSERT INTO categories (name) VALUE ('Drinks');
INSERT INTO categories (name) VALUE ('Cookies');
INSERT INTO categories (name) VALUE ('Floss Specials');
INSERT INTO categories (name) VALUE ('Bagels');
INSERT INTO categories (name) VALUE ('Focaccia');
INSERT INTO categories (name) VALUE ('Brioche');
INSERT INTO categories (name) VALUE ('Danish Rolls');
INSERT INTO categories (name) VALUE ('Scones');
INSERT INTO categories (name) VALUE ('Doughnuts');
INSERT INTO categories (name) VALUE ('Muffins');
INSERT INTO categories (name) VALUE ('Crullers');
INSERT INTO categories (name) VALUE ('Éclairs');
INSERT INTO categories (name) VALUE ('Macarons');
INSERT INTO categories (name) VALUE ('Madeleines');
INSERT INTO categories (name) VALUE ('Churros');
INSERT INTO categories (name) VALUE ('Cannoli');
INSERT INTO categories (name) VALUE ('Croissants');
INSERT INTO categories (name) VALUE ('Pita Bread');
INSERT INTO categories (name) VALUE ('Banana Bread');
INSERT INTO categories (name) VALUE ('Pound Cake');
INSERT INTO categories (name) VALUE ('Red Velvet Cake');
INSERT INTO categories (name) VALUE ('Cheesecake');
INSERT INTO categories (name) VALUE ('Tartlets');
INSERT INTO categories (name) VALUE ('Fruit Tart');
INSERT INTO categories (name) VALUE ('Lemon Bars');
INSERT INTO categories (name) VALUE ('Brownies');
INSERT INTO categories (name) VALUE ('Blondies');
INSERT INTO categories (name) VALUE ('Cinnamon Rolls');
INSERT INTO categories (name) VALUE ('Apple Pie');
INSERT INTO categories (name) VALUE ('Pecan Pie');
INSERT INTO categories (name) VALUE ('Pumpkin Pie');
INSERT INTO categories (name) VALUE ('Baklava');
INSERT INTO categories (name) VALUE ('Lamingtons');
INSERT INTO categories (name) VALUE ('Mille-Feuille');
INSERT INTO categories (name) VALUE ('Pavlova');
INSERT INTO categories (name) VALUE ('Tiramisu');
INSERT INTO categories (name) VALUE ('Genoise');
INSERT INTO categories (name) VALUE ('Panettone');
INSERT INTO categories (name) VALUE ('Hot Cross Buns');
INSERT INTO categories (name) VALUE ('Rugelach');
INSERT INTO categories (name) VALUE ('Kouign-Amann');
INSERT INTO categories (name) VALUE ('Black Forest Cake');
INSERT INTO categories (name) VALUE ('Swiss Roll');