INSERT INTO categories (name) VALUES ('Buns');
INSERT INTO categories (name) VALUES ('Toasts');
INSERT INTO categories (name) VALUES ('Sandwiches');
INSERT INTO categories (name) VALUES ('Dry Cakes');
INSERT INTO categories (name) VALUES ('Cakes');
INSERT INTO categories (name) VALUES ('Cake Slices');
INSERT INTO categories (name) VALUES ('Seasonal Specials');
INSERT INTO categories (name) VALUES ('Pudding');
INSERT INTO categories (name) VALUES ('Drinks');
INSERT INTO categories (name) VALUES ('Cookies');
INSERT INTO categories (name) VALUES ('Floss Specials');
INSERT INTO categories (name) VALUES ('Bagels');
INSERT INTO categories (name) VALUES ('Focaccia');
INSERT INTO categories (name) VALUES ('Brioche');
INSERT INTO categories (name) VALUES ('Danish Rolls');
INSERT INTO categories (name) VALUES ('Scones');
INSERT INTO categories (name) VALUES ('Doughnuts');
INSERT INTO categories (name) VALUES ('Muffins');
INSERT INTO categories (name) VALUES ('Crullers');
INSERT INTO categories (name) VALUES ('Éclairs');
INSERT INTO categories (name) VALUES ('Macarons');
INSERT INTO categories (name) VALUES ('Madeleines');
INSERT INTO categories (name) VALUES ('Churros');
INSERT INTO categories (name) VALUES ('Cannoli');
INSERT INTO categories (name) VALUES ('Croissants');
INSERT INTO categories (name) VALUES ('Pita Bread');
INSERT INTO categories (name) VALUES ('Banana Bread');
INSERT INTO categories (name) VALUES ('Pound Cake');
INSERT INTO categories (name) VALUES ('Red Velvet Cake');
INSERT INTO categories (name) VALUES ('Cheesecake');
INSERT INTO categories (name) VALUES ('Tartlets');
INSERT INTO categories (name) VALUES ('Fruit Tart');
INSERT INTO categories (name) VALUES ('Lemon Bars');
INSERT INTO categories (name) VALUES ('Brownies');
INSERT INTO categories (name) VALUES ('Blondies');
INSERT INTO categories (name) VALUES ('Cinnamon Rolls');
INSERT INTO categories (name) VALUES ('Apple Pie');
INSERT INTO categories (name) VALUES ('Pecan Pie');
INSERT INTO categories (name) VALUES ('Pumpkin Pie');
INSERT INTO categories (name) VALUES ('Baklava');
INSERT INTO categories (name) VALUES ('Lamingtons');
INSERT INTO categories (name) VALUES ('Mille-Feuille');
INSERT INTO categories (name) VALUES ('Pavlova');
INSERT INTO categories (name) VALUES ('Tiramisu');
INSERT INTO categories (name) VALUES ('Genoise');
INSERT INTO categories (name) VALUES ('Panettone');
INSERT INTO categories (name) VALUES ('Hot Cross Buns');
INSERT INTO categories (name) VALUES ('Rugelach');
INSERT INTO categories (name) VALUES ('Kouign-Amann');
INSERT INTO categories (name) VALUES ('Black Forest Cake');
INSERT INTO categories (name) VALUES ('Swiss Roll');